#!/bin/sh
arg=("$1")

if [ "$arg" == "--copy" ]; then
    # Simply copy the selected password to the clipboard
    gopass ls --flat | dmenu | xargs --no-run-if-empty gopass show -c
elif [ "$arg" == "--dotool" ]; then
    # First pipe the selected name to gopass, encrypt it and type the password with xdotool.
    gopass ls --flat | dmenu | xargs --no-run-if-empty gopass show -f | head -n 1 | xdotool type --clearmodifiers --file -
else
    echo "argument error"
fi


